import { NextRequest, NextResponse } from "next/server";
import { getSupabaseServiceRoleClient } from "@/lib/supabase";
import {
  fetchEstimateDetail,
  upsertRequirements,
} from "@/lib/estimates";
import { logTimelineEntry } from "@/lib/timeline";

function composeRequirements(detail: Awaited<ReturnType<typeof fetchEstimateDetail>>) {
  if (!detail) {
    return "<p>No requirement data available yet.</p>";
  }
  const requirementItems = detail.artifacts.length
    ? detail.artifacts
        .map(
          (artifact, index) =>
            `<li><strong>R${index + 1}.</strong> Align insights from ${escapeHtml(artifact.filename)} with stakeholder acceptance criteria.</li>`,
        )
        .join("")
    : "<li><strong>R1.</strong> Capture baseline requirements once artifacts have been uploaded.</li>";
  return [
    `<h3>Functional Requirements</h3>`,
    `<ol>${requirementItems}</ol>`,
    `<h3>Non-Functional Considerations</h3>`,
    `<ul><li>Security: Enforce principle of least privilege and log every approval.</li><li>Performance: Target sub-second responses for common approval actions.</li><li>Reliability: Provide a rollback path for every stage transition.</li></ul>`,
  ].join("");
}

function escapeHtml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

export async function POST(
  _request: NextRequest,
  context: { params: Promise<{ id: string }> },
) {
  const { id: estimateId } = await context.params;
  const supabase = getSupabaseServiceRoleClient();
  const detail = await fetchEstimateDetail(supabase, estimateId);
  if (!detail) {
    return NextResponse.json({ error: "Estimate not found" }, { status: 404 });
  }

  const generatedContent = composeRequirements(detail);

  await upsertRequirements(supabase, estimateId, {
    content: generatedContent,
    validated: false,
    validated_by: null,
  });

  await logTimelineEntry(
    supabase,
    estimateId,
    "Requirements",
    "Requirements generated by Copilot",
    "Copilot",
  );

  const updatedDetail = await fetchEstimateDetail(supabase, estimateId);
  return NextResponse.json(updatedDetail, { status: 200 });
}

