import { NextRequest, NextResponse } from "next/server";
import { getSupabaseServiceRoleClient } from "@/lib/supabase";
import {
  fetchEstimateDetail,
  upsertBusinessCase,
} from "@/lib/estimates";
import { logTimelineEntry } from "@/lib/timeline";

function composeBusinessCase(detail: Awaited<ReturnType<typeof fetchEstimateDetail>>) {
  if (!detail) {
    return "<p>No project context available.</p>";
  }
  const artifactItems = detail.artifacts.length
    ? detail.artifacts
        .slice(0, 5)
        .map(
          (artifact) =>
            `<li><strong>${escapeHtml(artifact.filename)}</strong> · ${formatRelativeDate(artifact.created_at)}</li>`,
        )
        .join("")
    : "<li>No supporting artifacts uploaded yet.</li>";

  return [
    `<h3>Executive Summary</h3>`,
    `<p>Project <strong>${escapeHtml(detail.estimate.name)}</strong> led by <strong>${escapeHtml(detail.estimate.owner)}</strong> is currently tracking through the <em>${escapeHtml(detail.estimate.stage)}</em> stage.</p>`,
    `<h3>Goals &amp; Outcomes</h3>`,
    `<ul><li>Deliver a high-confidence proposal with clear ROI evidence.</li><li>Align stakeholders on scope, constraints, and success metrics.</li><li>Ensure approvals are auditable via the stage timeline.</li></ul>`,
    `<h3>Supporting Artifacts</h3>`,
    `<ul>${artifactItems}</ul>`,
    `<h3>Next Steps</h3>`,
    `<ol><li>Review this draft with delivery and finance stakeholders.</li><li>Capture final edits directly in the editor.</li><li>Approve to unlock the Requirements stage.</li></ol>`,
  ].join("");
}

function formatRelativeDate(value: string) {
  try {
    const date = new Date(value);
    return date.toLocaleDateString();
  } catch {
    return value;
  }
}

function escapeHtml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

export async function POST(
  _request: NextRequest,
  context: { params: Promise<{ id: string }> },
) {
  const { id: estimateId } = await context.params;
  const supabase = getSupabaseServiceRoleClient();
  const detail = await fetchEstimateDetail(supabase, estimateId);
  if (!detail) {
    return NextResponse.json({ error: "Estimate not found" }, { status: 404 });
  }

  const generatedContent = composeBusinessCase(detail);

  await upsertBusinessCase(supabase, estimateId, {
    content: generatedContent,
    approved: false,
    approved_by: null,
  });

  await logTimelineEntry(
    supabase,
    estimateId,
    "Business Case",
    "Business Case generated by Copilot",
    "Copilot",
  );

  const updatedDetail = await fetchEstimateDetail(supabase, estimateId);
  return NextResponse.json(updatedDetail, { status: 200 });
}

