import { NextRequest, NextResponse } from "next/server";
import { getSupabaseServiceRoleClient } from "@/lib/supabase";
import {
  fetchEstimateDetail,
  upsertSolutionArchitecture,
} from "@/lib/estimates";
import { logTimelineEntry } from "@/lib/timeline";

function composeSolutionArchitecture(detail: Awaited<ReturnType<typeof fetchEstimateDetail>>) {
  if (!detail) {
    return "<p>No project context available.</p>";
  }

  // Extract key information from previous stages
  const businessCaseContent = detail.businessCase?.content || "";
  const requirementsContent = detail.requirements?.content || "";
  
  // Extract artifact content summaries
  const artifactSummaries = detail.artifacts
    .filter((a) => a.extract?.extraction_status === "ready" && a.extract.summary)
    .map((a) => `- ${a.filename}: ${a.extract!.summary}`)
    .join("\n");

  return [
    `<h3>Proposed Approach</h3>`,
    `<p>Based on the business case and requirements, we propose the following solution architecture:</p>`,
    `<ul>`,
    `<li>Leverage modern web technologies for responsive, performant user experience</li>`,
    `<li>Implement structured workflows with clear stage gates and approval processes</li>`,
    `<li>Integrate AI-powered Copilot for natural language interactions and content generation</li>`,
    `<li>Ensure data persistence and auditability through comprehensive timeline tracking</li>`,
    `</ul>`,
    `<h3>Technical Stack</h3>`,
    `<ul>`,
    `<li><strong>Frontend:</strong> Next.js 16 with React 19, TipTap for rich text editing, CopilotKit for AI integration</li>`,
    `<li><strong>Backend:</strong> LangGraph agent (Python) for LLM orchestration, FastAPI for API endpoints</li>`,
    `<li><strong>Database:</strong> Supabase (PostgreSQL) for structured data, Supabase Storage for artifacts</li>`,
    `<li><strong>AI:</strong> OpenAI/Anthropic via LangChain for content generation and analysis</li>`,
    `</ul>`,
    `<h3>Key Risks & Mitigations</h3>`,
    `<ul>`,
    `<li><strong>LLM Latency:</strong> Implement caching and optimistic UI updates to maintain responsiveness</li>`,
    `<li><strong>Data Consistency:</strong> Use Supabase transactions and version tracking for critical operations</li>`,
    `<li><strong>User Experience:</strong> Provide clear feedback during async operations and maintain state synchronization</li>`,
    `<li><strong>Scalability:</strong> Design with horizontal scaling in mind, leverage Supabase's managed infrastructure</li>`,
    `</ul>`,
    artifactSummaries ? `<h3>Context from Artifacts</h3><ul>${artifactSummaries.split("\n").map(s => `<li>${escapeHtml(s.replace(/^-\s*/, ""))}</li>`).join("")}</ul>` : "",
  ].join("");
}

function escapeHtml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

export async function POST(
  _request: NextRequest,
  context: { params: Promise<{ id: string }> },
) {
  const { id: estimateId } = await context.params;
  const supabase = getSupabaseServiceRoleClient();
  const detail = await fetchEstimateDetail(supabase, estimateId);
  if (!detail) {
    return NextResponse.json({ error: "Estimate not found" }, { status: 404 });
  }

  const generatedContent = composeSolutionArchitecture(detail);

  await upsertSolutionArchitecture(supabase, estimateId, {
    content: generatedContent,
    approved: false,
    approved_by: null,
  });

  await logTimelineEntry(
    supabase,
    estimateId,
    "Solution/Architecture",
    "Solution & Architecture generated by Copilot",
    "Copilot",
  );

  const updatedDetail = await fetchEstimateDetail(supabase, estimateId);
  return NextResponse.json(updatedDetail, { status: 200 });
}

