import { NextRequest, NextResponse } from "next/server";
import { getSupabaseServiceRoleClient } from "@/lib/supabase";
import {
  fetchEstimateDetail,
  replaceWbsRows,
} from "@/lib/estimates";
import { generateWbsFromDetail } from "@/lib/wbs";
import { logTimelineEntry } from "@/lib/timeline";

export async function POST(
  _request: NextRequest,
  context: { params: Promise<{ id: string }> },
) {
  const { id: estimateId } = await context.params;
  const supabase = getSupabaseServiceRoleClient();
  const detail = await fetchEstimateDetail(supabase, estimateId);
  if (!detail) {
    return NextResponse.json({ error: "Estimate not found" }, { status: 404 });
  }

  const generatedRows = generateWbsFromDetail(detail);

  try {
    await replaceWbsRows(
      supabase,
      estimateId,
      generatedRows.map((row) => ({
        taskCode: row.taskCode,
        description: row.description,
        role: row.role,
        hours: row.hours,
        assumptions: row.assumptions,
      })),
    );

    await logTimelineEntry(
      supabase,
      estimateId,
      "Effort Estimate",
      "WBS generated by Copilot",
      "Copilot",
    );

    const updatedDetail = await fetchEstimateDetail(supabase, estimateId);
    return NextResponse.json(updatedDetail, { status: 200 });
  } catch (error) {
    console.error("[effort-generate]", error);
    return NextResponse.json(
      { error: error instanceof Error ? error.message : "Unable to generate WBS" },
      { status: 500 },
    );
  }
}

